// Generated by mock_gen
#include <gmock/gmock.h>
#include "csv.h"

using ::testing::Return;
using ::testing::_;


class c_mock
{
public:
    c_mock() {
        ON_CALL(*this, csv_length(_)).WillByDefault(Return(0));
    }

    MOCK_METHOD1(csv_length, int(const char *csv_str));
};
